name = "replace-with-your-worker-name"
main = "worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

routes = [
  { pattern = "sub.example.com", custom_domain = true }
]

[[kv_namespaces]]
binding = "KV"
id = "replace-with-your-kv-namespace-id"
